# Generated by Django 4.2.3 on 2023-08-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
