# Generated by Django 4.2.3 on 2023-08-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0005_tag_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount of this ingredient in the recipe, e.g., in grams')),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mat.fooditem')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodList',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mat.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='mat.RecipeIngredient', to='mat.fooditem'),
        ),
    ]
