# Generated by Django 4.2.3 on 2023-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0007_recipeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='weight_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
